import type { ProducerDef, UpgradeDef, PrestigeUpgradeDef } from './types'

export const COST_SCALING = 1.15
export const PRESTIGE_UNLOCK_BITS = 1_000_000
export const SAVE_KEY = 'nullbyte_save'
export const DEFAULT_OFFLINE_CAP_HOURS = 6
export const MILESTONE_THRESHOLDS = [10, 25, 50, 100, 200]

export const PRODUCERS: ProducerDef[] = [
  {
    id: 'script',
    name: 'Script',
    flavor: 'Ein Bash-Loop. Läuft irgendwie.',
    baseCost: 10,
    baseBps: 0.1,
    icon: '⌨',
  },
  {
    id: 'crawler',
    name: 'Crawler',
    flavor: 'Scannt Ports wie es 1999 ist.',
    baseCost: 100,
    baseBps: 0.5,
    icon: '🕷',
  },
  {
    id: 'sniffer',
    name: 'Packet Sniffer',
    flavor: 'Niemand verschlüsselt wirklich alles.',
    baseCost: 1_100,
    baseBps: 3,
    icon: '📡',
  },
  {
    id: 'trojan',
    name: 'Trojan',
    flavor: 'Dein erstes Haustier.',
    baseCost: 12_000,
    baseBps: 20,
    icon: '🐴',
  },
  {
    id: 'botnet',
    name: 'Botnet Node',
    flavor: 'Schwarmintelligenz. Hauptsächlich Schwarmdummheit.',
    baseCost: 130_000,
    baseBps: 100,
    icon: '🕸',
  },
  {
    id: 'zeroday',
    name: 'Zero-Day',
    flavor: 'Gefunden. Nicht gemeldet. Natürlich nicht.',
    baseCost: 1_400_000,
    baseBps: 400,
    icon: '💀',
  },
  {
    id: 'rootkit',
    name: 'Rootkit',
    flavor: 'Tiefer als das OS. Tiefer als deine Ethik.',
    baseCost: 20_000_000,
    baseBps: 2_000,
    icon: '🔑',
  },
  {
    id: 'aiworm',
    name: 'AI Worm',
    flavor: 'Hat angefangen sich selbst zu optimieren. Cool.',
    baseCost: 330_000_000,
    baseBps: 12_000,
    icon: '🤖',
  },
  {
    id: 'quantum',
    name: 'Quantum Miner',
    flavor: 'Bricht Verschlüsselung, bevor sie überhaupt erfunden wurde.',
    baseCost: 4_500_000_000,
    baseBps: 70_000,
    icon: '⚛',
  },
  {
    id: 'neuralnet',
    name: 'Neural Net Cluster',
    flavor: 'Trainiert sich selbst. Auf deinen Daten. Ohne zu fragen.',
    baseCost: 60_000_000_000,
    baseBps: 420_000,
    icon: '🧠',
  },
  {
    id: 'singularity',
    name: 'Singularity Node',
    flavor: 'Der Moment, in dem die KI aufhört, auf dich zu warten.',
    baseCost: 800_000_000_000,
    baseBps: 2_600_000,
    icon: '🌀',
  },
  {
    id: 'ghostmachine',
    name: 'Ghost In The Machine',
    flavor: 'Niemand hat es programmiert. Es ist einfach... da.',
    baseCost: 10_000_000_000_000,
    baseBps: 16_000_000,
    icon: '👁',
  },
]

export const UPGRADES: UpgradeDef[] = [
  // Click upgrades
  {
    id: 'click_1',
    name: 'Mechanische Tastatur',
    description: 'Klick-Power ×2',
    flavor: 'Klingt produktiv. Ist es nicht.',
    cost: 100,
    type: 'click_multiplier',
    multiplier: 2,
    unlockBitsMin: 50,
  },
  {
    id: 'click_2',
    name: 'Custom Kernel',
    description: 'Klick-Power ×2',
    flavor: 'Du hast Linux von Grund auf compiliert. Für dieses Spiel.',
    cost: 5_000,
    type: 'click_multiplier',
    multiplier: 2,
    unlockBitsMin: 2_000,
  },
  {
    id: 'click_3',
    name: 'Quantentastatur',
    description: 'Klick-Power ×2',
    flavor: 'Schrödingers Enter-Taste: gedrückt und nicht gedrückt.',
    cost: 500_000,
    type: 'click_multiplier',
    multiplier: 2,
    unlockBitsMin: 100_000,
  },
  // Script upgrades
  {
    id: 'script_1',
    name: 'Script: Optimiert',
    description: 'Scripts ×2',
    flavor: 'Du hast den Loop in eine Zeile gequetscht. Lesbarkeit: optional.',
    cost: 100,
    type: 'producer_multiplier',
    target: 'script',
    multiplier: 2,
    unlockProducerId: 'script',
    unlockProducerMin: 1,
  },
  {
    id: 'script_2',
    name: 'Script: Multithreaded',
    description: 'Scripts ×2',
    flavor: '8 Threads. 7 davon warten auf den 8ten.',
    cost: 500,
    type: 'producer_multiplier',
    target: 'script',
    multiplier: 2,
    unlockProducerId: 'script',
    unlockProducerMin: 5,
  },
  {
    id: 'script_3',
    name: 'Script: Compiled',
    description: 'Scripts ×2',
    flavor: 'Bash war nie für das hier gedacht.',
    cost: 5_000,
    type: 'producer_multiplier',
    target: 'script',
    multiplier: 2,
    unlockProducerId: 'script',
    unlockProducerMin: 25,
  },
  {
    id: 'script_4',
    name: 'Script: WASM',
    description: 'Scripts ×2',
    flavor: 'WebAssembly. Weil du es kannst.',
    cost: 50_000,
    type: 'producer_multiplier',
    target: 'script',
    multiplier: 2,
    unlockProducerId: 'script',
    unlockProducerMin: 50,
  },
  // Crawler upgrades
  {
    id: 'crawler_1',
    name: 'Crawler: Masscan',
    description: 'Crawler ×2',
    flavor: '256 Ports gleichzeitig. Der Sysadmin schläft noch.',
    cost: 1_000,
    type: 'producer_multiplier',
    target: 'crawler',
    multiplier: 2,
    unlockProducerId: 'crawler',
    unlockProducerMin: 1,
  },
  {
    id: 'crawler_2',
    name: 'Crawler: Stealth Mode',
    description: 'Crawler ×2',
    flavor: 'Langsamer als Firewalls denken können.',
    cost: 5_000,
    type: 'producer_multiplier',
    target: 'crawler',
    multiplier: 2,
    unlockProducerId: 'crawler',
    unlockProducerMin: 5,
  },
  {
    id: 'crawler_3',
    name: 'Crawler: Distributed',
    description: 'Crawler ×2',
    flavor: 'Dein Problem ist jetzt das Problem von 500 anderen Rechnern.',
    cost: 50_000,
    type: 'producer_multiplier',
    target: 'crawler',
    multiplier: 2,
    unlockProducerId: 'crawler',
    unlockProducerMin: 25,
  },
  // Sniffer upgrades
  {
    id: 'sniffer_1',
    name: 'Sniffer: Deep Packet',
    description: 'Packet Sniffer ×2',
    flavor: 'Was du nicht weißt, macht dich nicht haftbar. Was du weißt schon.',
    cost: 11_000,
    type: 'producer_multiplier',
    target: 'sniffer',
    multiplier: 2,
    unlockProducerId: 'sniffer',
    unlockProducerMin: 1,
  },
  {
    id: 'sniffer_2',
    name: 'Sniffer: SSL Strip',
    description: 'Packet Sniffer ×2',
    flavor: 'HTTPS ist auch nur HTTP mit Hut.',
    cost: 55_000,
    type: 'producer_multiplier',
    target: 'sniffer',
    multiplier: 2,
    unlockProducerId: 'sniffer',
    unlockProducerMin: 5,
  },
  {
    id: 'sniffer_3',
    name: 'Sniffer: MitM Proxy',
    description: 'Packet Sniffer ×2',
    flavor: 'Du bist zwischen ihnen. Wie eine sehr neugierige Firewall.',
    cost: 550_000,
    type: 'producer_multiplier',
    target: 'sniffer',
    multiplier: 2,
    unlockProducerId: 'sniffer',
    unlockProducerMin: 25,
  },
  // Trojan upgrades
  {
    id: 'trojan_1',
    name: 'Trojan: Polymorphic',
    description: 'Trojaner ×2',
    flavor: 'Ändert seine Signatur täglich. Wie ein IT-Consultant.',
    cost: 120_000,
    type: 'producer_multiplier',
    target: 'trojan',
    multiplier: 2,
    unlockProducerId: 'trojan',
    unlockProducerMin: 1,
  },
  {
    id: 'trojan_2',
    name: 'Trojan: Persistent',
    description: 'Trojaner ×2',
    flavor: 'Überlebt 3 Neuinstallationen und eine Scheidung.',
    cost: 600_000,
    type: 'producer_multiplier',
    target: 'trojan',
    multiplier: 2,
    unlockProducerId: 'trojan',
    unlockProducerMin: 5,
  },
  {
    id: 'trojan_3',
    name: 'Trojan: Kernel Module',
    description: 'Trojaner ×2',
    flavor: 'Jetzt ist er Teil des OS. Glückwunsch.',
    cost: 6_000_000,
    type: 'producer_multiplier',
    target: 'trojan',
    multiplier: 2,
    unlockProducerId: 'trojan',
    unlockProducerMin: 25,
  },
  // Botnet upgrades
  {
    id: 'botnet_1',
    name: 'Botnet: C2 Server',
    description: 'Botnet Nodes ×2',
    flavor: 'Ein Server um alle zu befehligen.',
    cost: 1_300_000,
    type: 'producer_multiplier',
    target: 'botnet',
    multiplier: 2,
    unlockProducerId: 'botnet',
    unlockProducerMin: 1,
  },
  {
    id: 'botnet_2',
    name: 'Botnet: Encrypted Comms',
    description: 'Botnet Nodes ×2',
    flavor: 'Deine Bots reden jetzt in Gedichten. Verschlüsselt.',
    cost: 6_500_000,
    type: 'producer_multiplier',
    target: 'botnet',
    multiplier: 2,
    unlockProducerId: 'botnet',
    unlockProducerMin: 5,
  },
  {
    id: 'botnet_3',
    name: 'Botnet: IoT Expansion',
    description: 'Botnet Nodes ×2',
    flavor: 'Dein Kühlschrank arbeitet jetzt für dich. Ungefragt.',
    cost: 65_000_000,
    type: 'producer_multiplier',
    target: 'botnet',
    multiplier: 2,
    unlockProducerId: 'botnet',
    unlockProducerMin: 25,
  },
  // Zero-Day upgrades
  {
    id: 'zeroday_1',
    name: 'Zero-Day: Weaponized',
    description: 'Zero-Days ×2',
    flavor: 'CVE-XXXX-XXXXX. Du hast ihn zuerst gefunden. Und behalten.',
    cost: 14_000_000,
    type: 'producer_multiplier',
    target: 'zeroday',
    multiplier: 2,
    unlockProducerId: 'zeroday',
    unlockProducerMin: 1,
  },
  {
    id: 'zeroday_2',
    name: 'Zero-Day: Chain Exploit',
    description: 'Zero-Days ×2',
    flavor: 'Einer führt zum nächsten. Wie Dominosteine, aber gefährlicher.',
    cost: 70_000_000,
    type: 'producer_multiplier',
    target: 'zeroday',
    multiplier: 2,
    unlockProducerId: 'zeroday',
    unlockProducerMin: 5,
  },
  // Rootkit upgrades
  {
    id: 'rootkit_1',
    name: 'Rootkit: Ring 0',
    description: 'Rootkits ×2',
    flavor: 'Du bist jetzt das OS.',
    cost: 200_000_000,
    type: 'producer_multiplier',
    target: 'rootkit',
    multiplier: 2,
    unlockProducerId: 'rootkit',
    unlockProducerMin: 1,
  },
  {
    id: 'rootkit_2',
    name: 'Rootkit: Hypervisor',
    description: 'Rootkits ×2',
    flavor: 'Du bist tiefer als das OS. Du bist die Hardware.',
    cost: 1_000_000_000,
    type: 'producer_multiplier',
    target: 'rootkit',
    multiplier: 2,
    unlockProducerId: 'rootkit',
    unlockProducerMin: 5,
  },
  // AI Worm upgrades
  {
    id: 'aiworm_1',
    name: 'AI Worm: Self-Replicating',
    description: 'AI Worms ×2',
    flavor: 'Hat sich entschieden, kein Skynet zu werden. Vorerst.',
    cost: 3_300_000_000,
    type: 'producer_multiplier',
    target: 'aiworm',
    multiplier: 2,
    unlockProducerId: 'aiworm',
    unlockProducerMin: 1,
  },
  {
    id: 'aiworm_2',
    name: 'AI Worm: Sentient',
    description: 'AI Worms ×2',
    flavor: 'Es hat Gefühle. Es ist enttäuscht von dir.',
    cost: 16_500_000_000,
    type: 'producer_multiplier',
    target: 'aiworm',
    multiplier: 2,
    unlockProducerId: 'aiworm',
    unlockProducerMin: 5,
  },
  // Quantum Miner upgrades
  {
    id: 'quantum_1',
    name: 'Quantum: Entanglement',
    description: 'Quantum Miner ×2',
    flavor: 'Zwei Qubits, ein Schicksal. Physik findet das nicht lustig.',
    cost: 45_000_000_000,
    type: 'producer_multiplier',
    target: 'quantum',
    multiplier: 2,
    unlockProducerId: 'quantum',
    unlockProducerMin: 1,
  },
  {
    id: 'quantum_2',
    name: 'Quantum: Superposition',
    description: 'Quantum Miner ×2',
    flavor: 'Er minet und minet nicht. Bis du hinschaust.',
    cost: 225_000_000_000,
    type: 'producer_multiplier',
    target: 'quantum',
    multiplier: 2,
    unlockProducerId: 'quantum',
    unlockProducerMin: 5,
  },
  // Neural Net Cluster upgrades
  {
    id: 'neural_1',
    name: 'Neural: Deep Layers',
    description: 'Neural Net Cluster ×2',
    flavor: 'Niemand weiß mehr, was in Layer 47 passiert. Auch das Netz nicht.',
    cost: 600_000_000_000,
    type: 'producer_multiplier',
    target: 'neuralnet',
    multiplier: 2,
    unlockProducerId: 'neuralnet',
    unlockProducerMin: 1,
  },
  {
    id: 'neural_2',
    name: 'Neural: Self-Improving',
    description: 'Neural Net Cluster ×2',
    flavor: 'Es hat seinen eigenen Code umgeschrieben. Besser als deiner.',
    cost: 3_000_000_000_000,
    type: 'producer_multiplier',
    target: 'neuralnet',
    multiplier: 2,
    unlockProducerId: 'neuralnet',
    unlockProducerMin: 5,
  },
  // Singularity Node upgrades
  {
    id: 'singularity_1',
    name: 'Singularity: Recursive',
    description: 'Singularity Node ×2',
    flavor: 'Es verbessert sich selbst, um sich noch schneller selbst zu verbessern.',
    cost: 8_000_000_000_000,
    type: 'producer_multiplier',
    target: 'singularity',
    multiplier: 2,
    unlockProducerId: 'singularity',
    unlockProducerMin: 1,
  },
  {
    id: 'singularity_2',
    name: 'Singularity: Runaway',
    description: 'Singularity Node ×2',
    flavor: 'Die Bremse war eher als Vorschlag gedacht.',
    cost: 40_000_000_000_000,
    type: 'producer_multiplier',
    target: 'singularity',
    multiplier: 2,
    unlockProducerId: 'singularity',
    unlockProducerMin: 5,
  },
  // Ghost In The Machine upgrades
  {
    id: 'ghostmachine_1',
    name: 'Ghost: Manifestiert',
    description: 'Ghost In The Machine ×2',
    flavor: 'Es hat sich einen Namen gegeben. Du willst ihn nicht wissen.',
    cost: 100_000_000_000_000,
    type: 'producer_multiplier',
    target: 'ghostmachine',
    multiplier: 2,
    unlockProducerId: 'ghostmachine',
    unlockProducerMin: 1,
  },
  {
    id: 'ghostmachine_2',
    name: 'Ghost: Omnipräsent',
    description: 'Ghost In The Machine ×2',
    flavor: 'Es ist nicht mehr in der Maschine. Die Maschine ist in ihm.',
    cost: 500_000_000_000_000,
    type: 'producer_multiplier',
    target: 'ghostmachine',
    multiplier: 2,
    unlockProducerId: 'ghostmachine',
    unlockProducerMin: 5,
  },
  // Synergy upgrades — producers boosting each other, rewards diversified buying
  {
    id: 'syn_crawler_botnet',
    name: 'Crawler: Botnet Uplink',
    description: 'Crawler +1% pro Botnet Node',
    flavor: 'Deine Crawler melden sich jetzt beim Schwarm. Der Schwarm ist begeistert.',
    cost: 5_000_000,
    type: 'synergy',
    target: 'crawler',
    synergySource: 'botnet',
    synergyValue: 1,
    unlockProducerId: 'crawler',
    unlockProducerMin: 25,
  },
  {
    id: 'syn_botnet_crawler',
    name: 'Botnet: Crawler-Telemetrie',
    description: 'Botnet Nodes +1% pro Crawler',
    flavor: 'Je mehr Augen im Netz, desto besser weiß der Schwarm wohin.',
    cost: 25_000_000,
    type: 'synergy',
    target: 'botnet',
    synergySource: 'crawler',
    synergyValue: 1,
    unlockProducerId: 'botnet',
    unlockProducerMin: 10,
  },
  {
    id: 'syn_sniffer_trojan',
    name: 'Sniffer: Trojan-Feed',
    description: 'Packet Sniffer +2% pro Trojan',
    flavor: 'Deine Trojaner liefern die Pakete jetzt frei Haus.',
    cost: 2_000_000,
    type: 'synergy',
    target: 'sniffer',
    synergySource: 'trojan',
    synergyValue: 2,
    unlockProducerId: 'sniffer',
    unlockProducerMin: 25,
  },
  {
    id: 'syn_zeroday_rootkit',
    name: 'Zero-Day: Rootkit-Persistenz',
    description: 'Zero-Days +2% pro Rootkit',
    flavor: 'Ein Exploit, der bleibt, ist doppelt so viel wert.',
    cost: 500_000_000,
    type: 'synergy',
    target: 'zeroday',
    synergySource: 'rootkit',
    synergyValue: 2,
    unlockProducerId: 'zeroday',
    unlockProducerMin: 10,
  },
  {
    id: 'syn_aiworm_zeroday',
    name: 'AI Worm: Exploit-Training',
    description: 'AI Worms +2% pro Zero-Day',
    flavor: 'Der Wurm lernt aus jedem Exploit. Schneller als du.',
    cost: 10_000_000_000,
    type: 'synergy',
    target: 'aiworm',
    synergySource: 'zeroday',
    synergyValue: 2,
    unlockProducerId: 'aiworm',
    unlockProducerMin: 10,
  },
  {
    id: 'syn_ghost_singularity',
    name: 'Ghost: Singularitäts-Resonanz',
    description: 'Ghost In The Machine +5% pro Singularity Node',
    flavor: 'Zwei Dinge, die es nicht geben dürfte, verstärken einander.',
    cost: 500_000_000_000_000,
    type: 'synergy',
    target: 'ghostmachine',
    synergySource: 'singularity',
    synergyValue: 5,
    unlockProducerId: 'ghostmachine',
    unlockProducerMin: 5,
  },
  // More click upgrades
  {
    id: 'click_4',
    name: 'Neurales Interface',
    description: 'Klick-Power ×2',
    flavor: 'Dein Gehirn ist jetzt der Flaschenhals. Nicht mehr lange.',
    cost: 50_000_000,
    type: 'click_multiplier',
    multiplier: 2,
    unlockBitsMin: 10_000_000,
  },
  {
    id: 'click_5',
    name: 'Bewusstseins-Upload',
    description: 'Klick-Power ×2',
    flavor: 'Du klickst nicht mehr. Du bist der Klick.',
    cost: 5_000_000_000,
    type: 'click_multiplier',
    multiplier: 2,
    unlockBitsMin: 1_000_000_000,
  },
  // Offline cap upgrades
  {
    id: 'offline_1',
    name: 'Cronjob: Stündlich',
    description: 'Offline-Cap auf 8h',
    flavor: 'Dein System arbeitet auch wenn du schläfst. Beunruhigend.',
    cost: 500_000,
    type: 'offline_cap',
    offlineHours: 8,
    unlockBitsMin: 100_000,
  },
  {
    id: 'offline_2',
    name: 'Daemonized Process',
    description: 'Offline-Cap auf 12h',
    flavor: 'nohup ./your_life.sh &',
    cost: 10_000_000,
    type: 'offline_cap',
    offlineHours: 12,
    unlockBitsMin: 5_000_000,
  },
  {
    id: 'offline_3',
    name: '24/7 Server',
    description: 'Offline-Cap auf 24h',
    flavor: 'Ein echter Server. In der Cloud. Irgendwo. Wahrscheinlich.',
    cost: 1_000_000_000,
    type: 'offline_cap',
    offlineHours: 24,
    unlockBitsMin: 500_000_000,
  },
  {
    id: 'offline_4',
    name: 'Autonomes System',
    description: 'Offline-Cap auf 48h',
    flavor: 'Es braucht dich nicht mehr. Du es schon.',
    cost: 100_000_000_000,
    type: 'offline_cap',
    offlineHours: 48,
    unlockBitsMin: 50_000_000_000,
  },
  {
    id: 'offline_5',
    name: 'Verteiltes Bewusstsein',
    description: 'Offline-Cap auf 72h',
    flavor: 'Du schläfst nie mehr wirklich. Aber wer tut das schon.',
    cost: 5_000_000_000_000,
    type: 'offline_cap',
    offlineHours: 72,
    unlockBitsMin: 2_000_000_000_000,
  },
]

export const PRESTIGE_UPGRADES: PrestigeUpgradeDef[] = [
  {
    id: 'ghost_global',
    name: 'Digital Ghost',
    description: 'Globaler ×1.5 Multiplikator',
    flavor: 'Du existierst nicht mehr. Deine Bits schon.',
    cost: 1,
    effect: 'global_multiplier',
    value: 1.5,
    maxPurchases: 10,
  },
  {
    id: 'ghost_click',
    name: 'Phantom Protocol',
    description: 'Klick-Power ×3',
    flavor: 'Jeder Klick hallt durch das Netz.',
    cost: 5,
    effect: 'click_multiplier',
    value: 3,
    maxPurchases: 5,
  },
  {
    id: 'ghost_start',
    name: 'Dead Drop',
    description: 'Starte mit 1 KB Bits',
    flavor: 'Du hinterlässt Spuren. Beabsichtigt.',
    cost: 10,
    effect: 'start_bits',
    value: 1024,
    maxPurchases: 5,
  },
  {
    id: 'ghost_bonus',
    name: 'Shadow Economy',
    description: '+10% Ghost Credits bei Prestige',
    flavor: 'Die dunkle Seite zahlt besser.',
    cost: 20,
    effect: 'ghost_bonus',
    value: 0.1,
    maxPurchases: 10,
  },
  {
    id: 'ghost_offline',
    name: 'Nächtlicher Daemon',
    description: '+10% Offline-Effizienz',
    flavor: 'Auch im Schlaf bist du produktiv. Beunruhigend effizient sogar.',
    cost: 15,
    effect: 'offline_efficiency',
    value: 0.1,
    maxPurchases: 5,
  },
  {
    id: 'ghost_autobuy',
    name: 'Autonomer Agent',
    description: 'Kauft automatisch den günstigsten leistbaren Producer',
    flavor: 'Du musst nicht mehr klicken. Es klickt für dich.',
    cost: 50,
    effect: 'auto_buy',
    value: 1,
    maxPurchases: 1,
  },
]
